config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 1. see all task
  get "tasks", to: "tasks#index"
  # 2. view task details (one task)
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  # 3. add a task
  post "tasks", to: "tasks#create"
  # 4. Edit a task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  # 5. I can remove a task
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy] 

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(strong_params)
    @task.save!
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(strong_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def strong_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= form_for @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.label :completed %>
  <%= t.check_box :completed %>

  <%= t.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<div class="all">
  <% @tasks.each do |task| %>
    <div class="tasks">
      <i id="box" class="far fa-check-square"></i>
      <%= link_to task.title, task_path(task), id: "title" %>
      <%= link_to ('<i class="fas fa-trash"></i>').html_safe, delete_task_path(task), method: :delete, data: { confirm: "Are you sure you would like to DELETE" + " " + task.title }, id: "delete" %>
    </div>
  <% end %>
</div>

<%= link_to "Create Task", tasks_new_path, id:"create" %>

app/views/tasks/new.html.erb
<h1>Create a New task</h1>

<%= form_for @task do |t| %>
  <div class="title-box">
    <%= t.label :title %>
    <div class="boxes">
      <%= t.text_field :title %>
    </div>
  </div>

  <div class="title-box">
    <%= t.label :details %>
    <div class="boxes">
      <%= t.text_field :details %>
    </div>
  </div>

  <div class="title-box">
  <%= t.submit %>
  </div>

<% end %>

app/views/tasks/show.html.erb
<h1>My Tasks</h1>
<p><%= @task.title %>, <%= @task.details %>, Complete = <%= @task.completed %></p>
<%= link_to "Back to list", tasks_path(@task) %>
<%= link_to "Edit task",  edit_task_path %>